package views.panels;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Type;
import models.TypeCRUD;
import views.JFrameMain;

/**
 *
 * @author USER
 */
public class JPanelArticle extends javax.swing.JPanel {
    
    private JFrameMain jFrameMain;
    /**
     * Creates new form JPanelArticle
     */
    public JPanelArticle(JFrameMain jFrameMain, JPanelMain jpanel) {
        jFrameMain = jFrameMain;
        jPanelMain = jpanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton4 = new javax.swing.JToggleButton();
        jPanelBackground = new javax.swing.JPanel();
        jLabelTittle = new javax.swing.JLabel();
        jToggleButtonRegister = new javax.swing.JToggleButton();
        jToggleButtonUpdate = new javax.swing.JToggleButton();

        jToggleButton4.setText("Registrar");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelBackground.setBackground(new java.awt.Color(244, 225, 208));

        jLabelTittle.setBackground(new java.awt.Color(51, 51, 51));
        jLabelTittle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(244, 225, 208));
        jLabelTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTittle.setText("GESTOR DE PRODUCTOS");
        jLabelTittle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelTittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTittle.setOpaque(true);

        jToggleButtonRegister.setBackground(new java.awt.Color(255, 51, 0));
        jToggleButtonRegister.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jToggleButtonRegister.setForeground(new java.awt.Color(244, 225, 208));
        jToggleButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ADD_PRODUCT - copiaa.png"))); // NOI18N
        jToggleButtonRegister.setText(" REGISTRAR ");
        jToggleButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegisterEvenListenerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegisterEvenListenerMouseExited(evt);
            }
        });
        jToggleButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRegisterActionPerformed(evt);
            }
        });

        jToggleButtonUpdate.setBackground(new java.awt.Color(54, 125, 86));
        jToggleButtonUpdate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jToggleButtonUpdate.setForeground(new java.awt.Color(244, 225, 208));
        jToggleButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descarga.png"))); // NOI18N
        jToggleButtonUpdate.setText(" MODIFICAR ");
        jToggleButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUpdateEvenListenerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseExited(evt);
            }
        });
        jToggleButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jToggleButtonRegister)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonUpdate)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonRegister)
                    .addComponent(jToggleButtonUpdate))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonUpdateActionPerformed
        
        JPanelUpdateArticleByCode jpra = new JPanelUpdateArticleByCode(jFrameMain,jPanelMain);
        jPanelMain.initPanel(jpra);
        
    }//GEN-LAST:event_jToggleButtonUpdateActionPerformed

    private void jButtonUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseExited
        jToggleButtonUpdate.setBackground(new Color(54,125,86));
    }//GEN-LAST:event_jButtonUpdateMouseExited

    private void jButtonUpdateEvenListenerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateEvenListenerMouseEntered
        jToggleButtonUpdate.setBackground(new Color(68,95,59));
    }//GEN-LAST:event_jButtonUpdateEvenListenerMouseEntered

    private void jToggleButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRegisterActionPerformed
        JPanelRegisterArticle jpra = new JPanelRegisterArticle(jFrameMain, jPanelMain);
        jPanelMain.initPanel(jpra);

        TypeCRUD tcrud = new TypeCRUD();
        ArrayList<Type> types = new ArrayList<>();
        try {
            types = tcrud.getTypes();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelArticle.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i = 0; i < types.size(); i++) {
            jpra.getjComboBox2().addItem(types.get(i).getName());
        }

        jpra.getjComboBox1().addItem("MASCULINO");
        jpra.getjComboBox1().addItem("FEMENINO");
        jpra.getjComboBox1().addItem("UNISEX");

    }//GEN-LAST:event_jToggleButtonRegisterActionPerformed

    private void jButtonRegisterEvenListenerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterEvenListenerMouseExited
        jToggleButtonRegister.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_jButtonRegisterEvenListenerMouseExited

    private void jButtonRegisterEvenListenerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterEvenListenerMouseEntered
        jToggleButtonRegister.setBackground(new Color(175,51,0));
    }//GEN-LAST:event_jButtonRegisterEvenListenerMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButtonRegister;
    private javax.swing.JToggleButton jToggleButtonUpdate;
    // End of variables declaration//GEN-END:variables
    private JPanelMain jPanelMain;
}
