package views.panels;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.Garment;
import models.GarmentCRUD;
import models.Purchase;
import models.PurchaseCRUD;
import models.Sale;
import models.SaleCRUD;
import views.JFrameMain;

/**
 *
 * @author USER
 */
public class JPanelBuy extends javax.swing.JPanel {
    
    private JFrameMain jFrameMain;
    /**
     * Creates new form JPanelArticle
     */
    public JPanelBuy(JFrameMain jFrameMain, JPanelMain jPanelMain) {
        this.jFrameMain = jFrameMain;
        this.jPanelMain = jPanelMain;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton4 = new javax.swing.JToggleButton();
        jPanelBackground = new javax.swing.JPanel();
        jLabelTittle = new javax.swing.JLabel();
        jToggleButtonRegister1 = new javax.swing.JToggleButton();
        jToggleButtonUpdate1 = new javax.swing.JToggleButton();

        jToggleButton4.setText("Registrar");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelBackground.setBackground(new java.awt.Color(244, 225, 208));

        jLabelTittle.setBackground(new java.awt.Color(51, 51, 51));
        jLabelTittle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(244, 225, 208));
        jLabelTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTittle.setText("GESTOR DE COMPRAS");
        jLabelTittle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelTittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTittle.setOpaque(true);

        jToggleButtonRegister1.setBackground(new java.awt.Color(255, 51, 0));
        jToggleButtonRegister1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jToggleButtonRegister1.setForeground(new java.awt.Color(244, 225, 208));
        jToggleButtonRegister1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image.png"))); // NOI18N
        jToggleButtonRegister1.setText(" REGISTRAR ");
        jToggleButtonRegister1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonRegister1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButtonRegister1jButtonRegisterEvenListenerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButtonRegister1jButtonRegisterEvenListenerMouseExited(evt);
            }
        });
        jToggleButtonRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRegister1ActionPerformed(evt);
            }
        });

        jToggleButtonUpdate1.setBackground(new java.awt.Color(54, 125, 86));
        jToggleButtonUpdate1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jToggleButtonUpdate1.setForeground(new java.awt.Color(244, 225, 208));
        jToggleButtonUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image (2).png"))); // NOI18N
        jToggleButtonUpdate1.setText("REEMBOLSAR");
        jToggleButtonUpdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButtonUpdate1jButtonUpdateEvenListenerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButtonUpdate1jButtonUpdateMouseExited(evt);
            }
        });
        jToggleButtonUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonUpdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jToggleButtonRegister1)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonUpdate1)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonRegister1)
                    .addComponent(jToggleButtonUpdate1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonRegister1jButtonRegisterEvenListenerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonRegister1jButtonRegisterEvenListenerMouseEntered
        jToggleButtonRegister1.setBackground(new Color(175,51,0));
    }//GEN-LAST:event_jToggleButtonRegister1jButtonRegisterEvenListenerMouseEntered

    private void jToggleButtonRegister1jButtonRegisterEvenListenerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonRegister1jButtonRegisterEvenListenerMouseExited
        jToggleButtonRegister1.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_jToggleButtonRegister1jButtonRegisterEvenListenerMouseExited

    private void jToggleButtonRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRegister1ActionPerformed
        JPanelRegisterBuy jprb = new JPanelRegisterBuy(jFrameMain,jPanelMain);
        jPanelMain.initPanel(jprb);
        
        try {
            jprb.getjTextField6().setText(String.valueOf(new PurchaseCRUD().getNextId()));
        } catch (SQLException ex) {
            Logger.getLogger(JPanelBuy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButtonRegister1ActionPerformed

    private void jToggleButtonUpdate1jButtonUpdateEvenListenerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonUpdate1jButtonUpdateEvenListenerMouseEntered
        jToggleButtonUpdate1.setBackground(new Color(68,95,59));
    }//GEN-LAST:event_jToggleButtonUpdate1jButtonUpdateEvenListenerMouseEntered

    private void jToggleButtonUpdate1jButtonUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonUpdate1jButtonUpdateMouseExited
        jToggleButtonUpdate1.setBackground(new Color(54,125,86));
    }//GEN-LAST:event_jToggleButtonUpdate1jButtonUpdateMouseExited

    private void jToggleButtonUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonUpdate1ActionPerformed
        JPanelReportUpdatePurchase jpus = new JPanelReportUpdatePurchase(jFrameMain,jPanelMain);
        jPanelMain.initPanel(jpus);
        
        ArrayList<Purchase> purchases = new ArrayList<>();
        try {
            purchases = new PurchaseCRUD().getPurchases();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelReports.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        defaultTableModel.addColumn("CODIGO");
        defaultTableModel.addColumn("PRODUCTO");
        defaultTableModel.addColumn("FECHA");
        defaultTableModel.addColumn("PRECIO UNITARIO");
        defaultTableModel.addColumn("CANTIDAD");
        defaultTableModel.addColumn("PRECIO TOTAL");
        defaultTableModel.addColumn("COMENTARIOS");

        for (Purchase purchase : purchases) {
            Object[] row = new Object[7];
            row[0] = purchase.getId();
            row[1] = purchase.getGarments();
            row[2] = purchase.getDateTime();
            row[3] = purchase.getUnitPrice();
            row[4] = purchase.getQuantity();
            row[5] = purchase.getTotal();
            row[6] = purchase.getComentaries();
            defaultTableModel.addRow(row);
        }
        
        jpus.getjTable1().setModel(defaultTableModel);
    }//GEN-LAST:event_jToggleButtonUpdate1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButtonRegister1;
    private javax.swing.JToggleButton jToggleButtonUpdate1;
    // End of variables declaration//GEN-END:variables
    private JPanelMain jPanelMain;
}
