package views.panels;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.Garment;
import models.GarmentCRUD;
import models.Purchase;
import models.PurchaseCRUD;
import models.Sale;
import models.SaleCRUD;
import views.JFrameMain;

/**
 *
 * @author USER
 */
public class JPanelReports extends javax.swing.JPanel {
    
    private JFrameMain jFrameMain;
    /**
     * Creates new form JPanelArticle
     */
    public JPanelReports(JFrameMain jFrameMain, JPanelMain jPanelMain) {
        this.jFrameMain = jFrameMain;
        this.jPanelMain = jPanelMain;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton4 = new javax.swing.JToggleButton();
        jPanelBackground = new javax.swing.JPanel();
        jToggleButtonSale = new javax.swing.JToggleButton();
        jToggleButtonBuy = new javax.swing.JToggleButton();
        jToggleButtonProducts = new javax.swing.JToggleButton();
        jLabelTittle = new javax.swing.JLabel();

        jToggleButton4.setText("Registrar");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelBackground.setBackground(new java.awt.Color(244, 225, 208));

        jToggleButtonSale.setBackground(new java.awt.Color(54, 125, 86));
        jToggleButtonSale.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jToggleButtonSale.setForeground(new java.awt.Color(244, 225, 208));
        jToggleButtonSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rebaja.png"))); // NOI18N
        jToggleButtonSale.setText(" VENTAS ");
        jToggleButtonSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButtonSaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButtonSaleMouseExited(evt);
            }
        });
        jToggleButtonSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSaleActionPerformed(evt);
            }
        });

        jToggleButtonBuy.setBackground(new java.awt.Color(54, 125, 86));
        jToggleButtonBuy.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jToggleButtonBuy.setForeground(new java.awt.Color(244, 225, 208));
        jToggleButtonBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ropa-limpia.png"))); // NOI18N
        jToggleButtonBuy.setText(" COMPRAS ");
        jToggleButtonBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButtonBuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButtonBuyMouseExited(evt);
            }
        });
        jToggleButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBuyActionPerformed(evt);
            }
        });

        jToggleButtonProducts.setBackground(new java.awt.Color(54, 125, 86));
        jToggleButtonProducts.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jToggleButtonProducts.setForeground(new java.awt.Color(244, 225, 208));
        jToggleButtonProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregar.png"))); // NOI18N
        jToggleButtonProducts.setText(" INVENTARIO ");
        jToggleButtonProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButtonProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButtonProductsMouseExited(evt);
            }
        });
        jToggleButtonProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonProductsActionPerformed(evt);
            }
        });

        jLabelTittle.setBackground(new java.awt.Color(51, 51, 51));
        jLabelTittle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(244, 225, 208));
        jLabelTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTittle.setText("REPORTES");
        jLabelTittle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelTittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTittle.setOpaque(true);

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jToggleButtonBuy)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonProducts)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonSale)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonSale, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBuyActionPerformed
        JPanelReportPurchases jprb = new JPanelReportPurchases(jFrameMain,jPanelMain);
        jPanelMain.initPanel(jprb);
        
        ArrayList<Purchase> purchases = new ArrayList<>();
        try {
            purchases = new PurchaseCRUD().getPurchases();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelReports.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        defaultTableModel.addColumn("CODIGO");
        defaultTableModel.addColumn("PRODUCTO");
        defaultTableModel.addColumn("FECHA");
        defaultTableModel.addColumn("PRECIO UNITARIO");
        defaultTableModel.addColumn("CANTIDAD");
        defaultTableModel.addColumn("PRECIO TOTAL");
        defaultTableModel.addColumn("COMENTARIOS");

        for (Purchase purchase : purchases) {
            Object[] row = new Object[7];
            row[0] = purchase.getId();
            row[1] = purchase.getGarments();
            row[2] = purchase.getDateTime();
            row[3] = purchase.getUnitPrice();
            row[4] = purchase.getQuantity();
            row[5] = purchase.getTotal();
            row[6] = purchase.getComentaries();
            defaultTableModel.addRow(row);
        }
        
        jprb.getjTable1().setModel(defaultTableModel);
    }//GEN-LAST:event_jToggleButtonBuyActionPerformed

    private void jToggleButtonProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonProductsActionPerformed
        JPanelReportsUpdateArticles jpra = new JPanelReportsUpdateArticles(jFrameMain,jPanelMain);
        jPanelMain.initPanel(jpra);
        
        ArrayList<Garment> garments = new ArrayList<>();
        try {
            garments = new GarmentCRUD().getGarments();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelReports.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        defaultTableModel.addColumn("CODIGO");
        defaultTableModel.addColumn("TIPO");
        defaultTableModel.addColumn("NOMBRE");
        defaultTableModel.addColumn("DESCRIPCION");
        defaultTableModel.addColumn("SEXO");
        defaultTableModel.addColumn("PRECIO DE COMPRA");
        defaultTableModel.addColumn("PRECIO DE VENTA");
        defaultTableModel.addColumn("STOCK");

        for (Garment garment : garments) {
            Object[] row = new Object[8];
            row[0] = garment.getCod();
            row[1] = garment.getNameType();
            row[2] = garment.getName();
            row[3] = garment.getDescription();
            row[4] = garment.getSex();
            row[5] = garment.getPricePurchase();
            row[6] = garment.getPriceSale();
            row[7] = garment.getStock();
            defaultTableModel.addRow(row);
        }
        
        jpra.getjTable1().setModel(defaultTableModel);
    }//GEN-LAST:event_jToggleButtonProductsActionPerformed

    private void jToggleButtonSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSaleActionPerformed
        JPanelReportSales jprs = new JPanelReportSales(jFrameMain,jPanelMain);
        jPanelMain.initPanel(jprs);
        
        ArrayList<Sale> sales = new ArrayList<>();
        try {
            sales = new SaleCRUD().getSales();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelReports.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        defaultTableModel.addColumn("CODIGO");
        defaultTableModel.addColumn("PRODUCTO");
        defaultTableModel.addColumn("FECHA");
        defaultTableModel.addColumn("PRECIO UNITARIO");
        defaultTableModel.addColumn("CANTIDAD");
        defaultTableModel.addColumn("PRECIO TOTAL");
        defaultTableModel.addColumn("COMENTARIOS");

        for (Sale sale : sales) {
            Object[] row = new Object[7];
            row[0] = sale.getId();
            row[1] = sale.getGarments();
            row[2] = sale.getDateTime();
            row[3] = sale.getUnitPrice();
            row[4] = sale.getQuantity();
            row[5] = sale.getTotal();
            row[6] = sale.getComentaries();
            defaultTableModel.addRow(row);
        }
        
        jprs.getjTable1().setModel(defaultTableModel);
    }//GEN-LAST:event_jToggleButtonSaleActionPerformed

    private void jToggleButtonBuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonBuyMouseEntered
        jToggleButtonBuy.setBackground(new Color(68,95,59));
    }//GEN-LAST:event_jToggleButtonBuyMouseEntered

    private void jToggleButtonBuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonBuyMouseExited
        jToggleButtonBuy.setBackground(new Color(54,125,86));
    }//GEN-LAST:event_jToggleButtonBuyMouseExited

    private void jToggleButtonProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonProductsMouseEntered
        jToggleButtonProducts.setBackground(new Color(68,95,59));
    }//GEN-LAST:event_jToggleButtonProductsMouseEntered

    private void jToggleButtonProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonProductsMouseExited
       jToggleButtonProducts.setBackground(new Color(54,125,86));
    }//GEN-LAST:event_jToggleButtonProductsMouseExited

    private void jToggleButtonSaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonSaleMouseExited
        jToggleButtonSale.setBackground(new Color(54,125,86));
    }//GEN-LAST:event_jToggleButtonSaleMouseExited

    private void jToggleButtonSaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonSaleMouseEntered
        jToggleButtonSale.setBackground(new Color(68,95,59));
    }//GEN-LAST:event_jToggleButtonSaleMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButtonBuy;
    private javax.swing.JToggleButton jToggleButtonProducts;
    private javax.swing.JToggleButton jToggleButtonSale;
    // End of variables declaration//GEN-END:variables
    private JPanelMain jPanelMain;
}
